
package webservice.cotadormoeda;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CotadorMoedas", targetNamespace = "http://cotadormoeda.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CotadorMoedas {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversorDeRealParaMoeda", targetNamespace = "http://cotadormoeda.webservice/", className = "webservice.cotadormoeda.ConversorDeRealParaMoeda")
    @ResponseWrapper(localName = "conversorDeRealParaMoedaResponse", targetNamespace = "http://cotadormoeda.webservice/", className = "webservice.cotadormoeda.ConversorDeRealParaMoedaResponse")
    @Action(input = "http://cotadormoeda.webservice/CotadorMoedas/conversorDeRealParaMoedaRequest", output = "http://cotadormoeda.webservice/CotadorMoedas/conversorDeRealParaMoedaResponse")
    public double conversorDeRealParaMoeda(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "conversorDeMoedaParaReal", targetNamespace = "http://cotadormoeda.webservice/", className = "webservice.cotadormoeda.ConversorDeMoedaParaReal")
    @ResponseWrapper(localName = "conversorDeMoedaParaRealResponse", targetNamespace = "http://cotadormoeda.webservice/", className = "webservice.cotadormoeda.ConversorDeMoedaParaRealResponse")
    @Action(input = "http://cotadormoeda.webservice/CotadorMoedas/conversorDeMoedaParaRealRequest", output = "http://cotadormoeda.webservice/CotadorMoedas/conversorDeMoedaParaRealResponse")
    public double conversorDeMoedaParaReal(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1);

}
