
package webservice.cotadormoeda;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CotadorMoedasService", targetNamespace = "http://cotadormoeda.webservice/", wsdlLocation = "http://localhost:8080/cotadorDeMoedasWS?wsdl")
public class CotadorMoedasService
    extends Service
{

    private final static URL COTADORMOEDASSERVICE_WSDL_LOCATION;
    private final static WebServiceException COTADORMOEDASSERVICE_EXCEPTION;
    private final static QName COTADORMOEDASSERVICE_QNAME = new QName("http://cotadormoeda.webservice/", "CotadorMoedasService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/cotadorDeMoedasWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        COTADORMOEDASSERVICE_WSDL_LOCATION = url;
        COTADORMOEDASSERVICE_EXCEPTION = e;
    }

    public CotadorMoedasService() {
        super(__getWsdlLocation(), COTADORMOEDASSERVICE_QNAME);
    }

    public CotadorMoedasService(WebServiceFeature... features) {
        super(__getWsdlLocation(), COTADORMOEDASSERVICE_QNAME, features);
    }

    public CotadorMoedasService(URL wsdlLocation) {
        super(wsdlLocation, COTADORMOEDASSERVICE_QNAME);
    }

    public CotadorMoedasService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, COTADORMOEDASSERVICE_QNAME, features);
    }

    public CotadorMoedasService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CotadorMoedasService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CotadorMoedas
     */
    @WebEndpoint(name = "CotadorMoedasPort")
    public CotadorMoedas getCotadorMoedasPort() {
        return super.getPort(new QName("http://cotadormoeda.webservice/", "CotadorMoedasPort"), CotadorMoedas.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CotadorMoedas
     */
    @WebEndpoint(name = "CotadorMoedasPort")
    public CotadorMoedas getCotadorMoedasPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://cotadormoeda.webservice/", "CotadorMoedasPort"), CotadorMoedas.class, features);
    }

    private static URL __getWsdlLocation() {
        if (COTADORMOEDASSERVICE_EXCEPTION!= null) {
            throw COTADORMOEDASSERVICE_EXCEPTION;
        }
        return COTADORMOEDASSERVICE_WSDL_LOCATION;
    }

}
