
package webservices;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MultiplicationService", targetNamespace = "http://webservices/", wsdlLocation = "http://localhost:8080/MultiplicationService/Multiplication?WSDL")
public class MultiplicationService
    extends Service
{

    private final static URL MULTIPLICATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException MULTIPLICATIONSERVICE_EXCEPTION;
    private final static QName MULTIPLICATIONSERVICE_QNAME = new QName("http://webservices/", "MultiplicationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/MultiplicationService/Multiplication?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MULTIPLICATIONSERVICE_WSDL_LOCATION = url;
        MULTIPLICATIONSERVICE_EXCEPTION = e;
    }

    public MultiplicationService() {
        super(__getWsdlLocation(), MULTIPLICATIONSERVICE_QNAME);
    }

    public MultiplicationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), MULTIPLICATIONSERVICE_QNAME, features);
    }

    public MultiplicationService(URL wsdlLocation) {
        super(wsdlLocation, MULTIPLICATIONSERVICE_QNAME);
    }

    public MultiplicationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MULTIPLICATIONSERVICE_QNAME, features);
    }

    public MultiplicationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MultiplicationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Multiplication
     */
    @WebEndpoint(name = "MultiplicationPort")
    public Multiplication getMultiplicationPort() {
        return super.getPort(new QName("http://webservices/", "MultiplicationPort"), Multiplication.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Multiplication
     */
    @WebEndpoint(name = "MultiplicationPort")
    public Multiplication getMultiplicationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices/", "MultiplicationPort"), Multiplication.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MULTIPLICATIONSERVICE_EXCEPTION!= null) {
            throw MULTIPLICATIONSERVICE_EXCEPTION;
        }
        return MULTIPLICATIONSERVICE_WSDL_LOCATION;
    }

}
