
package calculadordedistanciadoispontosws.calculador;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadorDeDistanciaDoisPontosService", targetNamespace = "http://calculador.calculadorDeDistanciaDoisPontosWS/", wsdlLocation = "http://localhost:8082/calculadorDeDistanciaDoisPontos?wsdl")
public class CalculadorDeDistanciaDoisPontosService
    extends Service
{

    private final static URL CALCULADORDEDISTANCIADOISPONTOSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORDEDISTANCIADOISPONTOSSERVICE_EXCEPTION;
    private final static QName CALCULADORDEDISTANCIADOISPONTOSSERVICE_QNAME = new QName("http://calculador.calculadorDeDistanciaDoisPontosWS/", "CalculadorDeDistanciaDoisPontosService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8082/calculadorDeDistanciaDoisPontos?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORDEDISTANCIADOISPONTOSSERVICE_WSDL_LOCATION = url;
        CALCULADORDEDISTANCIADOISPONTOSSERVICE_EXCEPTION = e;
    }

    public CalculadorDeDistanciaDoisPontosService() {
        super(__getWsdlLocation(), CALCULADORDEDISTANCIADOISPONTOSSERVICE_QNAME);
    }

    public CalculadorDeDistanciaDoisPontosService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORDEDISTANCIADOISPONTOSSERVICE_QNAME, features);
    }

    public CalculadorDeDistanciaDoisPontosService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORDEDISTANCIADOISPONTOSSERVICE_QNAME);
    }

    public CalculadorDeDistanciaDoisPontosService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORDEDISTANCIADOISPONTOSSERVICE_QNAME, features);
    }

    public CalculadorDeDistanciaDoisPontosService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadorDeDistanciaDoisPontosService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculadorDeDistanciaDoisPontos
     */
    @WebEndpoint(name = "CalculadorDeDistanciaDoisPontosPort")
    public CalculadorDeDistanciaDoisPontos getCalculadorDeDistanciaDoisPontosPort() {
        return super.getPort(new QName("http://calculador.calculadorDeDistanciaDoisPontosWS/", "CalculadorDeDistanciaDoisPontosPort"), CalculadorDeDistanciaDoisPontos.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadorDeDistanciaDoisPontos
     */
    @WebEndpoint(name = "CalculadorDeDistanciaDoisPontosPort")
    public CalculadorDeDistanciaDoisPontos getCalculadorDeDistanciaDoisPontosPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://calculador.calculadorDeDistanciaDoisPontosWS/", "CalculadorDeDistanciaDoisPontosPort"), CalculadorDeDistanciaDoisPontos.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORDEDISTANCIADOISPONTOSSERVICE_EXCEPTION!= null) {
            throw CALCULADORDEDISTANCIADOISPONTOSSERVICE_EXCEPTION;
        }
        return CALCULADORDEDISTANCIADOISPONTOSSERVICE_WSDL_LOCATION;
    }

}
