
package calculadordedistanciadoispontosws.calculador;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CalculadorDeDistanciaDoisPontos", targetNamespace = "http://calculador.calculadorDeDistanciaDoisPontosWS/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CalculadorDeDistanciaDoisPontos {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculador", targetNamespace = "http://calculador.calculadorDeDistanciaDoisPontosWS/", className = "calculadordedistanciadoispontosws.calculador.Calculador")
    @ResponseWrapper(localName = "calculadorResponse", targetNamespace = "http://calculador.calculadorDeDistanciaDoisPontosWS/", className = "calculadordedistanciadoispontosws.calculador.CalculadorResponse")
    @Action(input = "http://calculador.calculadorDeDistanciaDoisPontosWS/CalculadorDeDistanciaDoisPontos/calculadorRequest", output = "http://calculador.calculadorDeDistanciaDoisPontosWS/CalculadorDeDistanciaDoisPontos/calculadorResponse")
    public double calculador(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        double arg3);

}
