
package webservice.validadorcpfcnpj;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ValidadorCPFCNPJ", targetNamespace = "http://validadorcpfcnpj.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ValidadorCPFCNPJ {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "validadorCPFCNPJ", targetNamespace = "http://validadorcpfcnpj.webservice/", className = "webservice.validadorcpfcnpj.ValidadorCPFCNPJ_Type")
    @ResponseWrapper(localName = "validadorCPFCNPJResponse", targetNamespace = "http://validadorcpfcnpj.webservice/", className = "webservice.validadorcpfcnpj.ValidadorCPFCNPJResponse")
    @Action(input = "http://validadorcpfcnpj.webservice/ValidadorCPFCNPJ/validadorCPFCNPJRequest", output = "http://validadorcpfcnpj.webservice/ValidadorCPFCNPJ/validadorCPFCNPJResponse")
    public boolean validadorCPFCNPJ(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
