
package webservice.validadorcpfcnpj;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ValidadorCPFCNPJService", targetNamespace = "http://validadorcpfcnpj.webservice/", wsdlLocation = "http://localhost:8083/validadorCPFCNPJ?wsdl")
public class ValidadorCPFCNPJService
    extends Service
{

    private final static URL VALIDADORCPFCNPJSERVICE_WSDL_LOCATION;
    private final static WebServiceException VALIDADORCPFCNPJSERVICE_EXCEPTION;
    private final static QName VALIDADORCPFCNPJSERVICE_QNAME = new QName("http://validadorcpfcnpj.webservice/", "ValidadorCPFCNPJService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8083/validadorCPFCNPJ?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        VALIDADORCPFCNPJSERVICE_WSDL_LOCATION = url;
        VALIDADORCPFCNPJSERVICE_EXCEPTION = e;
    }

    public ValidadorCPFCNPJService() {
        super(__getWsdlLocation(), VALIDADORCPFCNPJSERVICE_QNAME);
    }

    public ValidadorCPFCNPJService(WebServiceFeature... features) {
        super(__getWsdlLocation(), VALIDADORCPFCNPJSERVICE_QNAME, features);
    }

    public ValidadorCPFCNPJService(URL wsdlLocation) {
        super(wsdlLocation, VALIDADORCPFCNPJSERVICE_QNAME);
    }

    public ValidadorCPFCNPJService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, VALIDADORCPFCNPJSERVICE_QNAME, features);
    }

    public ValidadorCPFCNPJService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidadorCPFCNPJService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ValidadorCPFCNPJ
     */
    @WebEndpoint(name = "ValidadorCPFCNPJPort")
    public ValidadorCPFCNPJ getValidadorCPFCNPJPort() {
        return super.getPort(new QName("http://validadorcpfcnpj.webservice/", "ValidadorCPFCNPJPort"), ValidadorCPFCNPJ.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ValidadorCPFCNPJ
     */
    @WebEndpoint(name = "ValidadorCPFCNPJPort")
    public ValidadorCPFCNPJ getValidadorCPFCNPJPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://validadorcpfcnpj.webservice/", "ValidadorCPFCNPJPort"), ValidadorCPFCNPJ.class, features);
    }

    private static URL __getWsdlLocation() {
        if (VALIDADORCPFCNPJSERVICE_EXCEPTION!= null) {
            throw VALIDADORCPFCNPJSERVICE_EXCEPTION;
        }
        return VALIDADORCPFCNPJSERVICE_WSDL_LOCATION;
    }

}
