
package webservice.cotadorcombustivel;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CotadorCombustivel", targetNamespace = "http://cotadorcombustivel.webservice/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CotadorCombustivel {


    /**
     * 
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "cotadorDeConbustivel", targetNamespace = "http://cotadorcombustivel.webservice/", className = "webservice.cotadorcombustivel.CotadorDeConbustivel")
    @ResponseWrapper(localName = "cotadorDeConbustivelResponse", targetNamespace = "http://cotadorcombustivel.webservice/", className = "webservice.cotadorcombustivel.CotadorDeConbustivelResponse")
    @Action(input = "http://cotadorcombustivel.webservice/CotadorCombustivel/cotadorDeConbustivelRequest", output = "http://cotadorcombustivel.webservice/CotadorCombustivel/cotadorDeConbustivelResponse")
    public double cotadorDeConbustivel(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns double
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "calculoValorGastoCombustivel", targetNamespace = "http://cotadorcombustivel.webservice/", className = "webservice.cotadorcombustivel.CalculoValorGastoCombustivel")
    @ResponseWrapper(localName = "calculoValorGastoCombustivelResponse", targetNamespace = "http://cotadorcombustivel.webservice/", className = "webservice.cotadorcombustivel.CalculoValorGastoCombustivelResponse")
    @Action(input = "http://cotadorcombustivel.webservice/CotadorCombustivel/calculoValorGastoCombustivelRequest", output = "http://cotadorcombustivel.webservice/CotadorCombustivel/calculoValorGastoCombustivelResponse")
    public double calculoValorGastoCombustivel(
        @WebParam(name = "arg0", targetNamespace = "")
        double arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        double arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
